version: '3'
services:
  mongo:
    image: mongo:4
    command: mongod --smallfiles --quiet --logpath=/dev/null
    ports:
      - 27017:27017
    restart: always
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test 
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     